name: Write last commit date
on:
  push:
    branches: [ main ]

jobs:
  stamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get latest commit date
        id: last
        run: |
          echo "COMMIT_DATE=$(git --no-pager log -1 --format=%cI)" >> $GITHUB_OUTPUT

      - name: Write stamp file
        run: |
          mkdir -p docs
          echo "${{ steps.last.outputs.COMMIT_DATE }}" > docs/last-commit.txt

      - name: Commit stamp (optional)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update last-commit stamp"
          file_pattern: "docs/last-commit.txt"
